version: '3'
services:
    postgres:
      image: postgres:latest
      container_name: postgres
      restart: always
      ports: 
        - "5432:5432"
      environment:
        POSTGRES_USER: "${DB_USER_ID}"
        POSTGRES_PASSWORD: "${DB_USER_PASSWORD}"
      volumes:
        - ./data:/var/lib/postgresql/data

# version: '3.1'

# services:
#   db:
#     image: mysql
#     restart: always
#     # command: --lower_case_table_names=1 # 대소문자 구분
#     container_name: reddit
#     environment:
#         # - MYSQL_DATABASE="{MY_SQL_DB_USER_ID}"
#         # - MYSQL_ROOT_PASSWORD="${MY_SQL_DB_USER_PASSWORD}"
#         - MYSQL_DATABASE=root
#         - MYSQL_ROOT_PASSWORD=password
#         - TZ=Asia/Seoul
#         - container_name=reddit
#     command:
#         - --character-set-server=utf8mb4
#         - --collation-server=utf8mb4_unicode_ci
#     volumes:
#         - ./db:/var/lib/mysql # db 볼륨 처리
#     ports:
#       - 3306:3306